a.out: main.o Pessoa.o Contigua.o
	g++ -o a.exe main.o Pessoa.o Contigua.o
main.o: main.cpp
	g++ -c main.cpp
Pessoa.o: Pessoa.cpp Pessoa.h
	g++ -c Pessoa.cpp
Contigua.o: Contigua.cpp Contigua.h
	g++ -c Contigua.cpp
	
clean:
	rm *.o
